version: '3.8'

services:
  expressjs:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo
    ports:
      - '27017:27017'

  redis:
    image: redis
    ports:
      - '6379:6379'
