version: '3.8'

services:
  expressjs:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    env_file:
      - .env
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis
    ports:
      - '6379:6379'
    env_file:
      - .env

volumes:
  mongodb-data:
